<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ClassLibrary1">
      <HintPath>..\shared\ClassLibrary1\bin\Debug\net10.0\ClassLibrary1.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
